spring.application.name=orcacast
spring.jpa.hibernate.ddl-auto=update
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile
spring.ai.openai.audio.transcription.options.model=whisper-large-v3
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB